services:
  frontend:
    container_name: bingov2-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env.production
    networks:
      - proxy
    depends_on:
      - backend

  backend:
    container_name: bingov2-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    networks:
      - proxy
      - bingo_internal
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: bingov2-mongo
    restart: unless-stopped
#    ports:
#      - "27018:27017"
    volumes:
      - ./data/mongo-bingo:/data/db
    networks:
      - bingo_internal

networks:
  proxy:
    external: true
  bingo_internal:
